// Fallback graph data — used when the API isn't reachable.
// Mirrors the seed data in src/migration_atlas/graph/seed.py so the frontend
// works as a standalone demo (e.g., on Vercel before the backend is deployed).

export const FALLBACK_GRAPH = {
  nodes: [
    // Countries
    { id: "mexico", name: "Mexico", kind: "country", foreign_born_us: 11400000, immigrant_share: 0.22, top_destination_state: "California", era: "modern", narrative: "Largest origin since 1980. Began with the 1848 Treaty of Guadalupe Hidalgo, accelerated through the Bracero Program (1942–64) and again after 1965." },
    { id: "india", name: "India", kind: "country", foreign_born_us: 3200000, immigrant_share: 0.06, era: "modern", narrative: "Second-largest origin. Modern wave is post-1965, dominated by professionals on H-1B and student F-1 visas." },
    { id: "china", name: "China", kind: "country", foreign_born_us: 3000000, immigrant_share: 0.06, era: "modern", narrative: "Third-largest origin. First wave during the 1848 Gold Rush, halted by the 1882 Chinese Exclusion Act. Modern wave after 1965." },
    { id: "philippines", name: "Philippines", kind: "country", foreign_born_us: 2100000, immigrant_share: 0.04, era: "modern", narrative: "Began after 1898 U.S. annexation. Large healthcare-worker pipeline post-1965." },
    { id: "cuba", name: "Cuba", kind: "country", foreign_born_us: 1700000, immigrant_share: 0.033, top_destination_state: "Florida", era: "cold-war", narrative: "Major waves followed the 1959 Revolution: Freedom Flights, Mariel, Balseros." },
    { id: "el-salvador", name: "El Salvador", kind: "country", foreign_born_us: 1600000, immigrant_share: 0.031, era: "modern", narrative: "Mass migration began with the 1979–92 civil war." },
    { id: "dominican-republic", name: "Dominican Republic", kind: "country", foreign_born_us: 1400000, immigrant_share: 0.027, top_destination_state: "New York", era: "cold-war" },
    { id: "guatemala", name: "Guatemala", kind: "country", foreign_born_us: 1400000, immigrant_share: 0.027, era: "modern" },
    { id: "vietnam", name: "Vietnam", kind: "country", foreign_born_us: 1400000, immigrant_share: 0.027, era: "cold-war", narrative: "Began with the April 1975 fall of Saigon." },
    { id: "colombia", name: "Colombia", kind: "country", foreign_born_us: 1200000, immigrant_share: 0.023, era: "modern" },
    { id: "honduras", name: "Honduras", kind: "country", foreign_born_us: 1100000, immigrant_share: 0.021, era: "modern" },
    { id: "venezuela", name: "Venezuela", kind: "country", foreign_born_us: 1100000, immigrant_share: 0.021, top_destination_state: "Florida", era: "modern" },
    { id: "south-korea", name: "South Korea", kind: "country", foreign_born_us: 1000000, immigrant_share: 0.019, era: "cold-war" },
    { id: "canada", name: "Canada", kind: "country", foreign_born_us: 800000, immigrant_share: 0.015, era: "historic" },
    { id: "haiti", name: "Haiti", kind: "country", foreign_born_us: 730000, immigrant_share: 0.014, era: "modern" },
    { id: "uk", name: "United Kingdom", kind: "country", foreign_born_us: 700000, immigrant_share: 0.014, era: "historic" },
    { id: "germany", name: "Germany", kind: "country", foreign_born_us: 540000, immigrant_share: 0.010, era: "historic" },
    { id: "brazil", name: "Brazil", kind: "country", foreign_born_us: 500000, immigrant_share: 0.010, era: "modern" },
    { id: "nigeria", name: "Nigeria", kind: "country", foreign_born_us: 480000, immigrant_share: 0.009, era: "modern" },
    { id: "pakistan", name: "Pakistan", kind: "country", foreign_born_us: 430000, immigrant_share: 0.008, era: "modern" },
    { id: "ireland", name: "Ireland", kind: "country", foreign_born_us: 130000, immigrant_share: 0.003, era: "historic" },
    { id: "italy", name: "Italy", kind: "country", foreign_born_us: 130000, immigrant_share: 0.003, era: "historic" },

    // Visas
    { id: "h-1b", name: "H-1B", kind: "visa", annual_cap: 85000, year_established: 1990, top_country: "India" },
    { id: "f-1", name: "F-1", kind: "visa", top_country: "India / China" },
    { id: "eb-5", name: "EB-5", kind: "visa", annual_cap: 10000, year_established: 1990 },
    { id: "family-based", name: "Family-Based", kind: "visa", year_established: 1965 },
    { id: "tps", name: "TPS", kind: "visa", year_established: 1990 },
    { id: "refugee", name: "Refugee / Asylee", kind: "visa", year_established: 1980 },
    { id: "tn", name: "TN (USMCA)", kind: "visa", year_established: 1994 },
    { id: "dv-lottery", name: "Diversity Lottery", kind: "visa", annual_cap: 50000, year_established: 1990 },
    { id: "l-1", name: "L-1", kind: "visa" },

    // Laws
    { id: "chinese-exclusion-1882", name: "Chinese Exclusion Act (1882)", kind: "law", year_enacted: 1882, year_repealed: 1943 },
    { id: "immigration-act-1924", name: "Immigration Act (1924)", kind: "law", year_enacted: 1924, year_repealed: 1965 },
    { id: "ina-1965", name: "Immigration & Nationality Act (1965)", kind: "law", year_enacted: 1965 },
    { id: "irca-1986", name: "IRCA (1986)", kind: "law", year_enacted: 1986 },
    { id: "immigration-act-1990", name: "Immigration Act (1990)", kind: "law", year_enacted: 1990 },
    { id: "refugee-act-1980", name: "Refugee Act (1980)", kind: "law", year_enacted: 1980 },
    { id: "daca-2012", name: "DACA (2012)", kind: "law", year_enacted: 2012 },
    { id: "bracero-1942", name: "Bracero Program (1942-64)", kind: "law", year_enacted: 1942, year_repealed: 1964 },

    // Industries
    { id: "tech", name: "Technology", kind: "industry", immigrant_share: 0.25 },
    { id: "healthcare", name: "Healthcare", kind: "industry", immigrant_share: 0.18 },
    { id: "construction", name: "Construction", kind: "industry", unauthorized_share: 0.15 },
    { id: "agriculture", name: "Agriculture", kind: "industry", unauthorized_share: 0.24 },
    { id: "hospitality", name: "Hospitality", kind: "industry", unauthorized_share: 0.08 },
  ],
  links: [
    { source: "india", target: "h-1b", kind: "uses-visa" },
    { source: "india", target: "f-1", kind: "uses-visa" },
    { source: "india", target: "l-1", kind: "uses-visa" },
    { source: "india", target: "eb-5", kind: "uses-visa" },
    { source: "china", target: "f-1", kind: "uses-visa" },
    { source: "china", target: "eb-5", kind: "uses-visa" },
    { source: "china", target: "h-1b", kind: "uses-visa" },
    { source: "mexico", target: "family-based", kind: "uses-visa" },
    { source: "mexico", target: "tn", kind: "uses-visa" },
    { source: "philippines", target: "family-based", kind: "uses-visa" },
    { source: "cuba", target: "refugee", kind: "uses-visa" },
    { source: "vietnam", target: "refugee", kind: "uses-visa" },
    { source: "el-salvador", target: "tps", kind: "uses-visa" },
    { source: "honduras", target: "tps", kind: "uses-visa" },
    { source: "haiti", target: "tps", kind: "uses-visa" },
    { source: "venezuela", target: "tps", kind: "uses-visa" },
    { source: "nigeria", target: "dv-lottery", kind: "uses-visa" },
    { source: "nigeria", target: "f-1", kind: "uses-visa" },
    { source: "canada", target: "tn", kind: "uses-visa" },
    { source: "uk", target: "l-1", kind: "uses-visa" },
    { source: "south-korea", target: "family-based", kind: "uses-visa" },
    { source: "pakistan", target: "f-1", kind: "uses-visa" },
    { source: "guatemala", target: "tps", kind: "uses-visa" },
    { source: "dominican-republic", target: "family-based", kind: "uses-visa" },

    { source: "chinese-exclusion-1882", target: "china", kind: "restricts" },
    { source: "immigration-act-1924", target: "italy", kind: "restricts" },
    { source: "immigration-act-1924", target: "ireland", kind: "restricts" },
    { source: "ina-1965", target: "india", kind: "enables" },
    { source: "ina-1965", target: "china", kind: "enables" },
    { source: "ina-1965", target: "philippines", kind: "enables" },
    { source: "ina-1965", target: "south-korea", kind: "enables" },
    { source: "ina-1965", target: "mexico", kind: "enables" },
    { source: "ina-1965", target: "pakistan", kind: "enables" },
    { source: "irca-1986", target: "mexico", kind: "legalized" },
    { source: "bracero-1942", target: "mexico", kind: "enables" },
    { source: "refugee-act-1980", target: "vietnam", kind: "enables" },
    { source: "refugee-act-1980", target: "cuba", kind: "enables" },

    { source: "immigration-act-1990", target: "h-1b", kind: "creates" },
    { source: "immigration-act-1990", target: "eb-5", kind: "creates" },
    { source: "immigration-act-1990", target: "dv-lottery", kind: "creates" },
    { source: "immigration-act-1990", target: "tps", kind: "creates" },
    { source: "ina-1965", target: "family-based", kind: "creates" },
    { source: "refugee-act-1980", target: "refugee", kind: "creates" },

    { source: "india", target: "tech", kind: "works-in" },
    { source: "china", target: "tech", kind: "works-in" },
    { source: "philippines", target: "healthcare", kind: "works-in" },
    { source: "india", target: "healthcare", kind: "works-in" },
    { source: "mexico", target: "construction", kind: "works-in" },
    { source: "mexico", target: "agriculture", kind: "works-in" },
    { source: "mexico", target: "hospitality", kind: "works-in" },
    { source: "el-salvador", target: "construction", kind: "works-in" },
    { source: "guatemala", target: "agriculture", kind: "works-in" },
    { source: "honduras", target: "construction", kind: "works-in" },
  ],
};
