"""Regenerate app/src/fallbackData.js from the canonical seed graph.

The frontend bundles a snapshot of the graph for the offline / no-backend
demo. That snapshot drifts as the seed graph grows. Run this script after
any change to migration_atlas.graph.seed to keep the bundle in sync.

Usage:
    make fallback
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from migration_atlas.graph.build import build_default  # noqa: E402

OUT_PATH = REPO_ROOT / "app" / "src" / "fallbackData.js"

PREAMBLE = """// Auto-generated by scripts/regen_fallback.py — do not edit by hand.
// This snapshot of the seed graph is bundled into the frontend so the offline
// demo (no backend reachable) renders something meaningful. Regenerate with:
//
//     make fallback
//

"""


def main() -> None:
    backend = build_default()
    g = backend.graph
    nodes = [{"id": nid, **dict(g.nodes[nid])} for nid in g.nodes]
    links = [
        {"source": u, "target": v, "kind": k, **{
            ak: av for ak, av in attrs.items() if ak != "kind"
        }}
        for u, v, k, attrs in g.edges(keys=True, data=True)
    ]
    payload = {"nodes": nodes, "links": links}

    body = (
        PREAMBLE
        + "export const FALLBACK_GRAPH = "
        + json.dumps(payload, indent=2, default=str)
        + ";\n"
    )
    OUT_PATH.write_text(body)
    print(f"Wrote {len(nodes)} nodes and {len(links)} links to {OUT_PATH}")


if __name__ == "__main__":
    main()
